[project]
name = "codealpha-carpricedetection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fidelemiakanda", email = "sefimiakanda@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
codealpha-carpricedetection = "codealpha_carpricedetection:main"

[build-system]
requires = ["uv_build>=0.12.4,<0.13.0"]
build-backend = "uv_build"
